name: coordinate_converter
description: "Package for converting between UTM, DMS and DD coordinates in the WGS84 ellipsoid model"
version: 1.2.3
homepage: https://github.com/eamnicoletti/coordinate_converter

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  proj4dart: ^2.0.0

dev_dependencies:
  test: ^1.25.15
  very_good_analysis: ^5.1.0
