name: coordinate_converter
description: "Package for converting between UTM, DMS and DD coordinates in the WGS84 ellipsoid model"
version: 0.3.0
homepage:

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
